### ISSUE TITLE
notebook 1, section links

### ISSUE THREAD

**Issue by Severrinn** [dlab-berkeley/Python-Geospatial-Fundamentals#13]
@meiqingli  In notebook 1, the section links don't navigate to different sections in the notebook.

**Comment by meiqingli** [comment]
@Severrinn, let me check. It works on my end though.

**Comment by meiqingli** [comment]
Hey @Severrinn, I don't seem to have this issue launching through both datahub or jupyter notebook. Could you elaborate? Thanks.

**Comment by Severrinn** [comment]
@meiqingli  I'm attaching a screenshot. It's the links under the "Sections" heading
<img width="556" alt="Screenshot 2024-03-21 at 12 40 53 PM" src="https://github.com/dlab-berkeley/Python-Geospatial-Fundamentals/assets/64810167/e157e6e6-fc90-499e-8bf2-e8e84d2da324">

**Comment by meiqingli** [comment]
Do they not link you to the respective sections when you click them? It works fine on my end.

**Comment by Severrinn** [comment]
I realized that I probably should have downloaded it instead of expecting to navigate it on github. It works on datahub
