### ISSUE TITLE
Runnning workshop on D-Lab Datahub

### ISSUE THREAD

**Issue by hikari-murayama** [dlab-berkeley/Python-Geospatial-Fundamentals#7]
Running these notebooks on the D-Lab Datahub returns the following error:
```
/opt/conda/lib/python3.8/site-packages/geopandas/_compat.py:106: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2). Conversions between both will be slow.
 warnings.warn(
```

I think this requires a more recent version of `shapely`

**Comment by hikari-murayama** [comment]
Upon more research we may need to downgrade PyGeos: 
https://github.com/geopandas/geopandas/issues/1793

**Comment by pssachdeva** [comment]
Works on DataHub smoothly now; DataHub has updated the default packages
