### ISSUE TITLE
Error while running on Binder link 

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/Python-Geospatial-Fundamentals#9]
Binder link is unable to load `geopandas` module. Could be similar to what we've previously encountered with DataHub, which appears solved now! 

Error Message Below:

`ImportError                               Traceback (most recent call last)
<ipython-input-1-d56b3a509eaf> in <module>
      1 import pandas as pd
----> 2 import geopandas as gpd
      3 
      4 import matplotlib # base python plotting library
      5 import matplotlib.pyplot as plt # submodule of matplotlib

/srv/conda/envs/notebook/site-packages/geopandas/__init__.py in <module>
----> 1 from geopandas._config import options  # noqa
      2 
      3 from geopandas.geoseries import GeoSeries  # noqa
      4 from geopandas.geodataframe import GeoDataFrame  # noqa
      5 from geopandas.array import points_from_xy  # noqa

/srv/conda/envs/notebook/site-packages/geopandas/_config.py in <module>
    124 use_pygeos = Option(
    125     key="use_pygeos",
--> 126     default_value=_default_use_pygeos(),
    127     doc=(
    128         "Whether to use PyGEOS to speed up spatial operations. The default is True "

/srv/conda/envs/notebook/site-packages/geopandas/_config.py in _default_use_pygeos()
    110 
    111 def _default_use_pygeos():
--> 112     import geopandas._compat as compat
    113 
    114     return compat.USE_PYGEOS

/srv/conda/envs/notebook/site-packages/geopandas/_compat.py in <module>
      6 
      7 import pandas as pd
----> 8 import pyproj
      9 import shapely
     10 import shapely.geos

/srv/conda/envs/notebook/site-packages/pyproj/__init__.py in <module>
     48 import warnings
     49 
---> 50 from pyproj import _datadir
     51 from pyproj._list import (  # noqa: F401
     52     get_angular_units_map,

ImportError: cannot import name '_datadir'`

**Comment by pssachdeva** [comment]
Closed by #17
